# Generated by Django 4.2.16 on 2024-11-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
