# Generated by Django 4.2.16 on 2024-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
